### ISSUE TITLE
Consider using the defer attribute instead of async for script tags [performance]

### ISSUE THREAD

**Issue by charlespwd** [smooth-code/loadable-components#258] opened 2019-03-07 14:34 UTC
## 🚀 Feature Proposal

It seems like the most performant way of loading scripts is to include them with `defer` instead of `async`. At least according to [this article](https://flaviocopes.com/javascript-async-defer/)

We'd be getting the following:
![image](https://user-images.githubusercontent.com/4990691/53963849-144b0180-40bc-11e9-9f36-a7abded99212.png)

Instead of:
![image](https://user-images.githubusercontent.com/4990691/53963874-1dd46980-40bc-11e9-8120-ba13ffdc8625.png)

And when it comes to SSR, it would mean the js would only execute _in order_ once the HTML is fully loaded.

**Comment by charlespwd** [comment] 2019-03-07 14:38
However, that would delay the DCL event. Thoughts?

**Comment by theKashey** [comment] 2019-03-07 21:18
Defer also maintain the right execution order for scripts, and scripts has to be executed __after_ DCL - so it's always a right way to go.

**Comment by neoziro** [comment] 2019-03-10 21:04
Scripts are not in the head, they are in the body. So I think `async` is better. In fact I inspired from next.js for that one. I don't think defer is better if we put it at the end of body.

**Comment by theKashey** [comment] 2019-03-10 21:17
@neoziro - it's not about script position, only about marking them as `defer`, _defering_ execution to the "body end".

**Comment by neoziro** [comment] 2019-03-10 23:06
@theKashey I understand, but I don't know if the `defer` attribute is useful when the script is placed at the end of the body. In the article, they talk about a script in the head of the page.

**Comment by theKashey** [comment] 2019-03-11 02:34
It would help to maintain the script execution order, which may matter (load the main/run chunk first)

**Comment by neoziro** [comment] 2019-03-11 07:21
I don’t want to maintain the script execution order, this is the point!

**Comment by theKashey** [comment] 2019-03-11 07:31
With async - script execution order is random
Without async - waterfall, without any "prefetching"
With defer - waterfall __with__ prefetching.

All scripts would be loaded simultaneously, and executed only when script before got executed. It's sounds a bit safer.

**Comment by neoziro** [comment] 2019-03-11 07:37
The webpack plugin handles it with a jsonp function. So it is totally safe today, it is more performant because the code is evaluated when loaded. With defer it is not the case. So async is the expected behaviour.

**Comment by theKashey** [comment] 2019-03-12 07:14
I tend to disagree. Just today we went to a little trouble, where order-dependent CSS got broken due to reverted order of chunk execution.
I am not 100% how it might be possible, while according to the module system module2 should be executed module1 (module1 depends on module2), but by fact, module2 got executed after.

They were in different chunks, assembled in a third chunk and so on. Execution order might be important.

**Comment by neoziro** [comment] 2019-03-12 07:17
There is already methods to specify additional props, I propose to make a change, if `async={false}` is passed, then we remove the async tag. And we can also add `defer`. So we let the user customize that part. I prefer to stay with `async` by default.

**Comment by charlespwd** [comment] 2019-03-13 11:26
For what it's worth, moving the scripts to the body with async instead of defer increased our (local) lighthouse score by 1.

**Comment by neoziro** [comment] 2019-03-13 14:26
@charlespwd +1 is good or not good?

**Comment by charlespwd** [comment] 2019-03-13 20:25
@neoziro, it's good in favor of async loading.

**Comment by neoziro** [comment] 2019-03-13 20:56
OK so I prefer to keep it like that for now. CSS is an edge case that could be addressed in other ways. Also assets loading order has been fixed in #266. It should work better now. Wait and see.

**Closed by neoziro** 2019-03-13 20:56 UTC

**Comment by theKashey** [comment] 2019-03-24 07:48
So - I am pretty sure async is a __wrong__ decision.

- `Defer` - run scripts, in the right order, __after__ page is fully loaded
- `Async` - run a script once it is ready. __before__ or __after__ page is fully loaded
- `React.hydrate` - merge with a __existing__ HTML

The __only__ variant, when react can `hydrate` __is defer__. In async mode DOM three could be not complete, by any reason, and the result would be just __broken__.
You might wait for DOM-ready, but it would be equal to `defer`, but less semantic and safe.

**Comment by neoziro** [comment] 2019-03-24 17:37
Let see what's going on on next : https://github.com/zeit/next.js/issues/6602

**Comment by gerardmrk** [comment] 2019-04-25 01:41
Can confirm async attribute messes up css styles on first page load. Using defer with webpack's ext-html-plugin resolves it, but i rather dynamically fetch script tags on server instead of injecting them at build time.

**Comment by yairkukielka** [comment] 2019-05-14 20:50
Defer isn't really more performant, as @charlespwd said. But it's necessary to guarantee order of script execution.

In some of my tests, using `async` worked on Chrome because it was trying to be 'smart' and guessing dependencies between scripts, but this was failing in other browsers. 

If you have 2 scripts and one depends (or should be executed before) the other script you should use `defer`, as @theKashey said.

I would suggest letting the developer choose (through options) which one of these script attributes to use.

**Comment by gerardmrk** [comment] 2019-05-14 21:55
I'm doing this for now as a temp workaround till they fix it (doesn't cover any edge cases):

```ts
private _replaceScriptAsyncToDefer = async (scriptTags: string) => {
  if (!scriptTags) {
    return Promise.resolve("");
  }

  return Promise.resolve(scriptTags.replace(/\sasync\s/g, " defer "));
};
```
https://github.com/gerardmrk/erogen/blob/master/app/client.web/src/renderer/index.tsx#L220

**Comment by neoziro** [comment] 2019-05-15 08:30
Yeah we should give the possibility to the user to choose between the two, I created an issue #337.

**Comment by yairkukielka** [comment] 2019-05-15 16:34
Thanks for opening that issue, @neoziro !

I was thinking of overriding the default behavior passing a function to `chunkExtractor.getScriptElements()`. According to the [documentation](https://www.smooth-code.com/open-source/loadable-components/docs/api-loadable-server/) you can pass a function to it, but reading the source code it looks like this wouldn't work (because it only expects an object). Should the docs be updated or should this behavior be implemented?

![loadable](https://user-images.githubusercontent.com/11599360/57792701-83645800-76f4-11e9-816d-6aeae221d5c1.png)

**Comment by neoziro** [comment] 2019-05-17 12:06
@yairkukielka the documentation and the code are up to date, see https://github.com/smooth-code/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L26

**Comment by yairkukielka** [comment] 2019-05-17 16:46
I missed this! Thanks for pointing it out! :)

**Comment by seeliang** [comment] 2020-01-31 00:18
to find out the details, I did this 
https://github.com/seeliang/client-side-performance/blob/master/load-fallback/index.html

hope it could help others

**Comment by shivang2joshi** [comment] 2020-06-16 09:06
So it turns out finally it is an option there. 
`
exractor.getScriptTags({ defer: true, anyAttrToScript: "youGotIt" });
`
This is reference to everyone who browses this issue should get the answer at last (this) comment. 😃  Please add this use case scenario in docs as well. @gregberge in Docs, it is not clear that exactly how the arguments should be passed and so eventually one has to check in the code how is it receiving the args. So, it will be easy and time saving for everyone if an example is provided there 🙏🏻  !

**Comment by markwoodward23** [comment] 2020-07-03 19:39
@shivang2joshi - I tried that but it purely adds to the scripts, rather than removing the async word. That's definitely hardcoded in: https://github.com/gregberge/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L46

In our case - we're loading script tags into the head, rather than the body, and want them to be defer. Our solution to this is to use the `getScriptElements` function on the extractor, then run them through a custom function to build the script tags with defer instead of async. 

```
  const buildScriptTags = arr =>
    arr
      .map(({ props }) => {
        if (props.id === '__LOADABLE_REQUIRED_CHUNKS__') {
          return `<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">${
            props.dangerouslySetInnerHTML.__html
          }</script>`;
        } else {
          return `<script ${Object.entries(props)
            .map(([key, val]) => {
              return key === 'async' ? 'defer' : `${key}="${val}"`;
            })
            .join(' ')}></script>`;
        }
      })
      .join('\n');

  const scripts = buildScriptTags(extractor.getScriptElements());
```

Not the best, but it works 🤷‍♂️

**Comment by shivang2joshi** [comment] 2020-07-04 01:09
> @shivang2joshi - I tried that but it purely adds to the scripts, rather than removing the async word. That's definitely hardcoded in: https://github.com/gregberge/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L46
> 
> 
> 
> In our case - we're loading script tags into the head, rather than the body, and want them to be defer. Our solution to this is to use the `getScriptElements` function on the extractor, then run them through a custom function to build the script tags with defer instead of async. 
> 
> 
> 
> ```
> 
>   const buildScriptTags = arr =>
> 
>     arr
> 
>       .map(({ props }) => {
> 
>         if (props.id === '__LOADABLE_REQUIRED_CHUNKS__') {
> 
>           return `<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">${
> 
>             props.dangerouslySetInnerHTML.__html
> 
>           }</script>`;
> 
>         } else {
> 
>           return `<script ${Object.entries(props)
> 
>             .map(([key, val]) => {
> 
>               return key === 'async' ? 'defer' : `${key}="${val}"`;
> 
>             })
> 
>             .join(' ')}></script>`;
> 
>         }
> 
>       })
> 
>       .join('\n');
> 
> 
> 
>   const scripts = buildScriptTags(extractor.getScriptElements());
> 
> ```
> 
> 
> 
> Not the best, but it works 🤷‍♂️ 

For your use case, [this](https://github.com/gregberge/loadable-components/issues/258#issuecomment-492424822) might work just fine. So simple, just replace async with defer in final output.
