### ISSUE TITLE
Hot reload not work in v1.2.0

### ISSUE THREAD

**Issue by wellyshen** [smooth-code/loadable-components#56] opened 2018-03-28 16:26 UTC
Hi I upgraded to v1.2.0 but I found my async component doesn't be hot reloaded without [this](https://github.com/gaearon/react-hot-loader#code-splitting) way.

**Comment by neoziro** [comment] 2018-03-29 09:01
It is weird, I tested it and it should work. As soon as I have a moment I will try to run your project to see what's going on.

**Comment by wellyshen** [comment] 2018-03-30 01:58
It can be reproduced via [this](https://github.com/wellyshen/react-cool-starter/tree/webpack-4) branch.

**Comment by Kmaschta** [comment] 2018-04-03 14:40
I can confirm: it works with `react-hot-loader`, but not without it, whether the config `hotReload` is enabled or not.

**Comment by neoziro** [comment] 2018-04-03 20:42
Oh maybe I was not clear but React Hot Loader is still required. But it is not required to put `hot(module)` in all loadable components.

**Comment by neoziro** [comment] 2018-04-05 21:30
@wellyshen problem solved? branch disappeared

**Comment by wellyshen** [comment] 2018-04-06 03:37
@neoziro Not yet. Sorry I moving the repo to [master](https://github.com/wellyshen/react-cool-starter). This issue still can be reproduced via the master branch.

**Comment by tommyalvarez** [comment] 2018-04-12 12:28
@wellyshen @neoziro same error with version 1.3.0

**Comment by neoziro** [comment] 2018-04-12 13:24
@tommyalvarez what error?

**Comment by tommyalvarez** [comment] 2018-04-13 12:41
@neoziro now i have a strange bug that no matter the route, it will always load the same Component. I think it has something to do with this: https://stackoverflow.com/questions/44349667/react-router-v4-rendering-wrong-component-but-matching-correctly  but since i'm not following the same pattern i'm not finding a clear way to solve it :S

**Comment by neoziro** [comment] 2018-04-13 15:41
You setup is not good, "module" must be the dist module, you have to put it in each file: "Dashbord.js", "Signin.js", etc...

But it should work without it, it is weird.

**Comment by tommyalvarez** [comment] 2018-04-13 15:47
@neoziro Oh, but if i do that, will it work once in production mode where there is no hot reload ?
I verified now and it works BUT i need to make two modifications to the file, it's like it falls one step behind. I have to make two different changes to the file for the HMR to work.

**Comment by neoziro** [comment] 2018-04-15 15:42
Yes as mentioned in [RHL readme](https://github.com/gaearon/react-hot-loader#install).

Yes I know that is very annoying... I would try to find a fix.

**Comment by neoziro** [comment] 2018-04-15 17:06
@wellyshen just tested it and it works in your project. Is the problem solved?

@tommyalvarez I tested it and Hot Reload works out of the box. Be careful of following all three steps: https://github.com/gaearon/react-hot-loader#getting-started

I close it, if Hot Reload does not work it is a problem of React Hot Loader setup.

**Closed by neoziro** 2018-04-15 17:06 UTC

**Comment by wellyshen** [comment] 2018-04-16 02:25
@neoziro It works with a component which is wrapped by `hot(module)`. The component (e.g. home) can't work without `hot(module)` in v1.3.0.

**Comment by neoziro** [comment] 2018-04-16 06:43
You can remove `hot(module)` in [Home](https://github.com/wellyshen/react-cool-starter/blob/master/src/pages/Home/Home.js#L57). I just tested it and it works. Only one at the root (App) and everything works.

**Comment by wellyshen** [comment] 2018-04-16 06:47
@neoziro Oh I think I know the reason. Because of the **react-router's route config API** so I'm using `<AppContainer>` instead of `hot(module)`. Can v1.3.0 works with `<AppContainer>` way?

**Comment by neoziro** [comment] 2018-04-16 06:50
@wellyshen I am not sure, I think `hot(module)` is required, sorry..

**Comment by wellyshen** [comment] 2018-04-16 06:51
@neoziro OK, I got it. Thank you for your time 👍
