### ISSUE TITLE
How to load all CSS chunk files before stream's on event?

### ISSUE THREAD

**Issue by hemmxwxsoo** [smooth-code/loadable-components#295] opened 2019-04-05 00:52 UTC
I've implemented a app with CSS Splitting. When I call `getStyleTags()` method before stream's on event, that only gives me a CSS file of app chunk. I'm not sure whether it is expected behavior. I want to compose `<head>` element with all CSS chunks. Could you give me a hint of where I should look?

```node.js
// write <head>.
console.log(chunkExtractors.client.getStyleTags());
/*
<link data-chunk="app" rel="stylesheet" href="/css/app_b7e0fdb35bc64627e91e.css">
*/        

stream.pipe(response, { end:false });
stream.on('end', () => {
    // close <html> with scripts.
    console.log(chunkExtractors.client.getStyleTags());
    /*
    <link data-chunk="app" rel="stylesheet" href="/css/app_b7e0fdb35bc64627e91e.css">
    <link data-chunk="Test" rel="stylesheet" href="/css/Test_b7e0fdb35bc64627e91e.css">
    <link data-chunk="Test2" rel="stylesheet" href="/css/Test2_b7e0fdb35bc64627e91e.css">
    */
});
```

**Comment by theKashey** [comment] 2019-04-05 01:12
Duplicate of #236

That's expected behaviour. The application is not rendered or just partially rendered by the time you call `chunkExtractors.client.getStyleTags` for the first time.
And waiting for a full render to be able to add used styles into the render - might be not something you want from _stream rendering_.

There are two options:
- use CSS-in-JS, like `emotion` or `styled-components` - they would interleave your HTML with used styles as styles got introduced. Probably not an option for a pure CSS solution.
- use [used-styles](https://github.com/theKashey/used-styles) to interleave your HTML stream with used styles as styles got used. Requires unique names for styles and some additional code to setup server.

**Comment by hemmxwxsoo** [comment] 2019-04-05 05:15
@theKashey, Thank you for your thoughtful answer. I've been trying to apply `used-styles`, but I think I have some duplicate styles with same classname throughout CSS files, so `style` parameter of `createStyleStream()`'s callback is assigned with unnecessary CSS files that don't need to be loaded. Or is there any way to wait for `getStyleTags()` to collect all CSS files?

**Comment by theKashey** [comment] 2019-04-05 05:39
No. The only "correct" time to "collect all CSS" is the end of the rendering.
You may use CSSModules to make your classnames "unique", as they should.

**Comment by hemmxwxsoo** [comment] 2019-04-05 08:28
I'm using Linaria, but the problem seems to be related to referring to each other component's class. I'm not sure. I should examine it. Thanks for your help. :D

**Closed** 2019-04-05 19:00 UTC
Labels: question ❓
