### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by antonybudianto** [smooth-code/loadable-components#85] opened 2018-05-15 10:47 UTC
Hi,

I'm doing SSR with HMR, when trying to change lazy loaded component, the HMR works on client side, but when I tried to refresh the page, the console is showing these errors:

```js
loadable-components.es.js:93 Uncaught Error: loadable-components: module "./NotFoundPage-1" is not found, client and server modules are not sync. You are probably not using the same resolver on server and client.
    at loadable-components.es.js:93
    at Array.map (<anonymous>)
    at loadState (loadable-components.es.js:87)
    at loadComponents (loadable-components.es.js:118)
    at Object.<anonymous> (client.js:25)
    at Object../src/renderer/client.js (app.js:1413)
    at __webpack_require__ (bootstrap:772)
    at fn (bootstrap:141)
    at Object.0 (app.js:1982)
    at __webpack_require__ (bootstrap:772)
```

<img width="576" alt="screen shot 2018-05-15 at 5 49 20 pm" src="https://user-images.githubusercontent.com/7658554/40053237-b8fab490-586a-11e8-812b-bfea3784691d.png">

How to Reproduce:
1. Clone https://github.com/antonybudianto/react-ssr-starter
2. npm i
3. npm start
4. Visit random 404 route (e.g http://localhost:3000/asdasd)
5. Change `src/routes/NotFoundPage/NotFoundPage.js`
    - This route is lazy loaded
6. Notice the hot reload should work
7. Refresh the page
8. Error shown

Any pointers will be helpful, thank you!

**Comment by antonybudianto** [comment] 2018-05-16 09:27
My current workaround is: :smile: 

```js
loadableState.getScriptTag().replace(/-[0-9]"/, '"')
```

**Comment by neoziro** [comment] 2018-05-17 09:47
Oh.. I know what is the problem, this is actually a real bug! Can you try to fix it?

**Comment by antonybudianto** [comment] 2018-05-17 09:58
Honestly I don't know where to start. Is it related to this file?
https://github.com/smooth-code/loadable-components/blob/master/src/componentTracker.js

**Comment by neoziro** [comment] 2018-05-17 10:10
Yeah it could be pretty complicated, just let go for now. I will create an issue to describe the exact problem.

**Comment by antonybudianto** [comment] 2018-05-23 15:35
Hi,

I can confirm the latest release fixed the issue, thanks @neoziro !

**Comment by ion-willo** [comment] 2018-07-16 13:15
Sorry to add on an old issue but we're getting this again on 2.2.2. The problem is that happens randomly so it's very hard to reproduce. Once it happens, it keeps happening until the the server is restarted.

**Comment by antonybudianto** [comment] 2018-08-02 12:26
Just updated to 2.2.2 and it's happening again. Can you help? @neoziro

**Comment by DXD23-SJTU** [comment] 2018-09-03 02:50
Have the same issue :(
When I import the same component in different routes, and try to reload from the server, it will appear.
```
loadable-components.es.js:105 Uncaught (in promise) Error: loadable-components: module "../../components/admin/publish-1" is not found, client and server modules are not sync. You are probably not using the same resolver on server and client.
    at eval (loadable-components.es.js:105)
    at Array.map (<anonymous>)
    at loadState (loadable-components.es.js:96)
    at loadComponents (loadable-components.es.js:130)
    at eval (index.jsx:427)
    at Object../client/pages/admin/index.jsx (admin.js:60)
    at __webpack_require__ (manifest.js:713)
    at fn (manifest.js:118)
    at eval (client:3)
    at Object.3 (admin.js:4283)
```

**Comment by jsauca** [comment] 2018-10-26 13:38
I have the same issue and errors as above with version Loadable Components 2.2.3 and Webpack HMR.
I have used the temporary solution of @antonybudianto and it is seems to be working.

**Comment by neoziro** [comment] 2018-10-29 13:47
HMR is not supported in the new version (I think @theKashey could have an idea to support it). I close it because it concerns loadable v2, feel free to reopen a new issue.

**Comment by mbrochh** [comment] 2018-11-01 02:02
@neoziro do I understand correctly that this problem will be solved in loadable v3, or even v4 (it seems you are working on v4 already?)

**Comment by neoziro** [comment] 2018-11-04 17:01
HMR is supported in v4, but React Hot Loader is not supported.

**Comment by theKashey** [comment] 2018-11-04 23:52
Not yet supported?

**Comment by neoziro** [comment] 2018-11-08 14:31
React Hot Loader is *maybe* supported 😅

**Comment by neoziro** [comment] 2018-11-13 09:20
I made a test using [razzle](https://github.com/jaredpalmer/razzle). Everything is working as expected. If you experience any problem with Hot Reloading, please open a new issue.

This one was about v2.x, today v5 has been rewritten from scratch and has nothing in common with this issue.

**Closed by neoziro** 2018-11-13 09:20 UTC
Labels: bug 🐛
