### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(loadable)' of undefined

### ISSUE THREAD

**Issue by max-mykhailenko** [smooth-code/loadable-components#10] opened 2017-07-21 07:41 UTC
Problem occurs while I work with server render and dynamic client code from webpack. Seems I have difference in module numbers when HMR recompile my client code.
Server rendering works throw babel-node and don't need webpack build.
```js
/* eslint-env browser */
function loadComponents() {
  if (typeof window === 'undefined') {
    throw new Error('`loadComponents` must be called client-side: `window` is undefined');
  }

  var ids = window[_constants.COMPONENT_IDS] || [];
  return Promise.all(ids.map(function (id) {
    return componentTracker.get(id)[_constants.LOADABLE]().load(); // error here
  }));
}
```

HTML contains IDS
`<script>window.__LOADABLE_COMPONENT_IDS__ = [6553];</script>`

Thanks!

**Comment by neoziro** [comment] 2017-07-21 13:58
Hello, can you please give me the full environment? 6553 is very huge number, I don't think you have 6553 code splitted modules!

**Comment by max-mykhailenko** [comment] 2017-07-22 14:53
I have only 4 chunks. I can't show you full code because I already switch it to my own solution.

**Comment by max-mykhailenko** [comment] 2017-07-23 09:25
Can you describe some parts of business logic?
* server renders html after `getLoadableState()` which needed for `loadableState.getScriptTag()`
* `getScriptTag()` return some components IDs
* page loads, `loadComponents()` loads components with IDs from previous step. Why do we need that? I thought that `BrowserRouter` should load modules according to routing.

So, why we need `loadComponents` and `getLoadableState`

**Comment by neoziro** [comment] 2017-07-24 06:32
It is needed to prevent the page blink at load. We have to require all modules before starting to render application.

**Comment by neoziro** [comment] 2017-07-24 06:33
I think you have a problem of server-side module caching, that's why the id is 6553.

**Comment by max-mykhailenko** [comment] 2017-07-24 07:26
I render server side (in development) using babel-node without webpack. Maybe problem there. What do you think?

**Comment by neoziro** [comment] 2017-07-24 10:01
I am doing the same and I don't have any problem...

**Comment by neoziro** [comment] 2017-07-24 13:15
Have you solved your problem? I would be happy to see all the stack to understand the problem. Do you have Hangout?

**Comment by max-mykhailenko** [comment] 2017-07-25 06:45
I didn't solve it. I move to my own solution. It's more verbose but without loop over the components tree. I download component corresponding to current route.
Client and server render also without promise resolving. Several routing files allows to achieve that.

**Comment by neoziro** [comment] 2017-07-25 07:56
@max-mykhailenko not very scalable but it works ;)

**Comment by grydstedt** [comment] 2017-10-18 23:49
I'm having this same issue. Any resolution to this?

**Comment by grydstedt** [comment] 2017-10-18 23:53
Seems like `componentTracker.get(id)` is empty. Also the id seems to change every render, even on the same page, so maybe loadable state is out of sync somehow?

**Comment by neoziro** [comment] 2017-10-19 02:35
Yes probably, I need to investigate it more deeply. Do you have any example repo to reproduce it?

**Comment by Alivejke** [comment] 2017-10-19 13:01
I also have it, so far I see that I have 16 bundles and it fails when it tries to get bundle number 17 that is not existing.

**Comment by neoziro** [comment] 2017-10-21 05:56
I have to investigate it. I think the approach is too simple and weak. Approach taken by [react-loadable](https://github.com/thejameskyle/react-loadable) is heavier but probably more resilient.

**Comment by Alivejke** [comment] 2017-10-22 13:52
Possible solution could be also passing this id as an argument for loadable() and using this passed id  not only for inner reference but also as generated bundle name (instead of 0.js, 1.js etc). Maybe it would be also an idea to investigate why loadable() is called this one additional time. Sorry didn't have time to dig deeper, have a lot of pressure on work and your library was a big help, thank you very much! :)

**Comment by Alivejke** [comment] 2017-10-31 15:39
I discovered one more problem with `Symbol(loadable)` in `index.js:115` in check `instance.constructor[_constants.LOADABLE]`. If you inspect `instance` in chrome dev tools you can find field `Symbol(loadable)` in the object, but if you try to access it - it returns undefined. The problem is reproducible only on production(webpack) build on server side.

**Comment by Mistereo** [comment] 2017-11-27 13:37
Same issue here.
In my case the reason (I guess) is that I have used `loadable` in non-main chunk, so component tracker don't know about this component when `loadComponents` called.

So it seems like all `loadable` calls should happen in main chunk.

**Comment by neoziro** [comment] 2017-11-27 15:32
It is a known issue, unfortunately I would not be able to solve it without a Babel plugin or some additional code. Still thinking about a simple way to do it.

**Comment by IcanDivideBy0** [comment] 2017-12-02 20:11
A disclamer about this in `README.md` could save some time and headaches

**Comment by FabioAntunes** [comment] 2018-01-05 16:16
I was having this issue, after adding:

* babel-plugin-syntax-dynamic-import on the client.
* babel-plugin-dynamic-import-node on the server.

it's fixed now.

**Comment by FabioAntunes** [comment] 2018-01-09 16:05
Would there be a easy way to disable code splitting on dev, based on some environment variable or webpack config? I don't mind not having code splitting during dev, it's more important that I don't have to kill the server to be able to refresh the page.

**Comment by neoziro** [comment] 2018-01-10 09:05
@FabioAntunes the [next version of React Hot Loader](https://github.com/gaearon/react-hot-loader/tree/next) will be compatible with Code Splitting. I think about a way to make it compatible with `loadable-components` with zero config.

**Comment by neoziro** [comment] 2018-02-02 14:53
This long issue is now solved in v1. I close this issue because it was relative to the previous version. Feel free to open an issue if you experience any problem with the new fresh v1 of loadable-components.

**Closed by neoziro** 2018-02-02 14:53 UTC
